#!/bin/bash

function prompt(){
    echo "Quit, or List All, or List account: "
}

prompt

while read command arguments
do
    
    case "$command" in
        List)
            if [[ "$arguments" == "All" ]]; then
                ./statement
            else
                ./onePerson "$arguments"
            fi
        ;;
        Quit)
            break
        ;;
        *)
           echo "$command not understood, List or Quit"
        ;;
    esac 
    prompt
done