#!/bin/bash



transactionFile="Transactions2014.csv"

name="$@"
echo "transactions for $name"

    echo
    echo credits
    join -t , -1 1 -2 2 -o 2.1,2.3,2.4,2.5 <(echo "$name") <(sort -t , -k 2 $transactionFile) 

    echo
    echo debits
    join -t , -1 1 -2 3 -o 2.1,2.2,2.4,2.5 <(echo "$name") <(sort -t , -k 3 $transactionFile) 
       
    credits=$( 
        awk "BEGIN { print $( (echo "0.0" && join -t , -1 1 -2 2 -o 2.5 <(echo "$name") <(sort -t , -k 2 $transactionFile) ) | 
        paste -sd+ - ) }"
    )

   
    debits=$(
        awk "BEGIN { print $( (echo "0.0" && join -t , -1 1 -2 3 -o 2.5 <(echo "$name") <(sort -t , -k 3 $transactionFile) ) | 
        paste -sd+ - ) }" 
     ) 

 

    balance=$( awk "BEGIN { print $credits-$debits }" )

    echo
    echo "$n $credits, -$debits, $balance"