#!/bin/bash


transactionFile=${1:-"Transactions2014.csv"}

./getPeople | while read n  
do 
    credits=$( 
       awk "BEGIN { print $( (echo "0.0" && join -t , -1 1 -2 2 -o 2.5 <(echo "$n") <(sort -t , -k 2 $transactionFile) ) | 
        paste -sd+ - ) }"
    )

    debits=$(
        awk "BEGIN { print $( (echo "0.0" && join -t , -1 1 -2 3 -o 2.5 <(echo "$n") <(sort -t , -k 3 $transactionFile) ) | 
        paste -sd+ - ) }" 
     ) 

     balance=$( awk "BEGIN { print $credits-$debits }" )
    echo "$n $credits, -$debits, $balance"
 
done


