#!/bin/bash

# key ideas:
# quotes to avoid expansion
# use $() to assign output
# 2> to redirect stderr
# && and ||

N='*.txt'
echo 'N is ${N} in single quotes'
echo "N is ${N} in double quotes"
echo N is ${N} without quotes
F=$(ls $N 2>/dev/null ) && echo "found $F" || echo "no $N"

N='*.zzz'
F=$(ls $N 2>/dev/null ) && echo "found $F" || echo "no $N"

